/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_gestionfiche (void);
GtkWidget* create_window_ajtfiche (void);
GtkWidget* create_window_modfiche (void);
GtkWidget* create_window_rechfiche (void);
GtkWidget* create_window_rdvfiche (void);
GtkWidget* create_window_integ (void);
GtkWidget* create_window_gestion (void);
GtkWidget* create_window_ajoute (void);
GtkWidget* create_window_modifier (void);
GtkWidget* create_window_afficher (void);
GtkWidget* create_window_ajets (void);
GtkWidget* create_window_gestionets (void);
GtkWidget* create_window_modets (void);
GtkWidget* create_window_rechets (void);
GtkWidget* create_window_gestiondons (void);
GtkWidget* create_window_ajdons (void);
GtkWidget* create_window_moddons (void);
GtkWidget* create_window_rechdons (void);
